spring:
  profiles:
    active: dev


server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
  
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics
  metrics:
    tags:
      application: concurrent-entity-change-logger
  prometheus:
    metrics:
      export:
        enabled: true