spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
  
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics,info
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: concurrent-entity-change-logger
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M